---
title: "Homework11"
author: "HudsonPlaskoff"
date: "2026-04-18"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nycflights13)
library(maps)
```

## Origin and Destination Pairs^[Question 1 complete]

```{r}
pairs <- flights %>%
  group_by(origin,dest) %>%
  summarize(
    n = n()
  )

knitr::kable(pairs %>% head())
```

## Latitudes and Longitudes of Origin Airports^[Question 2 complete]

```{r}
pairs <- pairs %>%
  left_join(airports, join_by(origin==faa)) %>%
  select(origin,dest,n,lon,lat) %>%
  rename(
    origin_lon = lon,
    origin_lat = lat
  ) %>%
  relocate(origin_lon, origin_lat, .before=dest)

knitr::kable(pairs %>% head())
```

## Latitudes and Longitudes of Destination Airports^[Question 3 complete]

```{r}
pairs <- pairs %>%
  left_join(airports, join_by(dest==faa)) %>%
  select(origin,origin_lon,origin_lat,dest,n,lon,lat) %>%
  rename(
    dest_lon = lon,
    dest_lat = lat
  ) %>%
  relocate(dest_lon, dest_lat, .before=n)

knitr::kable(pairs %>% head())
```

# Map of United States^[Question 4 complete]

```{r}
ggplot() +
  geom_polygon(
    data = map_data("state") ,
    mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = "gray"
  ) +
  coord_fixed(1.3)
```

# Map of United States with Flights^[Question 5 complete]

```{r}
ggplot(pairs) +
  geom_polygon(
    data = map_data("state") ,
    mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = "gray"
  ) +
  coord_fixed(1.3) +
  geom_segment(aes(
    x=origin_lon,
    xend=dest_lon,
    y=origin_lat,
    yend=dest_lat
      ),
    alpha=0.2
    )
```

# Map of United States with Filtered Flights^[Question 6 complete]

```{r}
ggplot() +
  geom_polygon(
    data = map_data("state") ,
    mapping = aes(x = long, y = lat, group = group),
    fill = NA, color = "gray"
  ) +
  coord_fixed(1.3) +
  geom_segment(
    data=pairs,
    mapping=aes(
      x=origin_lon,
      xend=dest_lon,
      y=origin_lat,
      yend=dest_lat
    ),
    alpha=0.2
    )
```